### ISSUE TITLE
Figure out and fix Dependabot warnings

### ISSUE THREAD

**Issue by vviers** [betagouv/a-just#2]
[https://github.com/betagouv/a-just/security/dependabot](https://github.com/betagouv/a-just/security/dependabot) is all light up in red. Given the sensitivity of the data we will eventually manipulate, it could be a good idea to fix them as they arise :)

**Comment by fxmontigny** [comment]
Ha !!! Dsl j'ai supprimé les notifications de github.
Faut que je vois car les modules qui sont affichés sont des dépendances. 
Je planifie ça dans le kanban  !
